### ISSUE TITLE
year issue

### ISSUE THREAD

**Issue by arg7** [lewisxhe/PCF8563_Library#2]
According to datasheet CENTURY_MASK should be set in byte at offset 5, not 4.

You should replace "_data[4] |= PCF8563_CENTURY_MASK;" with "_data[5] |= PCF8563_CENTURY_MASK;" at line n 91 and then also 93.

Then you should change line "year = cetury ?  1900 + year : 2000 + year;" to "year = !cetury ?  1900 + year : 2000 + year;" in order to get proper value for the year.

I have created pull request, if you wish to accept fix.

Best regards,
AR

**Comment by lewisxhe** [comment]
I just saw it now. Thank you for your repair

**Comment by ptrhess** [comment]
Per the datasheet for the PCF8563, the century bit is 0 for years 20XX, and 1 for years 19XX. While the above fix works, it works because the bit gets encoded incorrectly on the way in to the RTC, and then decoded in like fashion on the way back out of the RTC. The RTC itself will have the century bit set incorrectly.

**Comment by lewisxhe** [comment]
> Per the datasheet for the PCF8563, the century bit is 0 for years 20XX, and 1 for years 19XX. While the above fix works, it works because the bit gets encoded incorrectly on the way in to the RTC, and then decoded in like fashion on the way back out of the RTC. The RTC itself will have the century bit set incorrectly.

Thanks for the reminder, indeed the opposite has been fixed

**Comment by caveman99** [comment]
Thanks for the heads up, just a pointer that this library index for platformio is strange. Theres a 1.0.0 version from 3 years ago and 0.0.1 plus 0.0.2 (the tags from here). The newest one is now released as 1.0.0 which will not be picked up there cause there already is an older release with the same number. I think you need to release a 'dummy' 1.0.1 to superseed this.

**Comment by caveman99** [comment]
Reference for this: https://registry.platformio.org/libraries/lewisxhe/PCF8563_Library/versions

**Comment by lewisxhe** [comment]
It has been updated. Wait for a while to see if the platformio will get the version number normally
